### ISSUE TITLE
Undefined is not an object

### ISSUE THREAD

**Issue by retr00h** [ViroCommunity/starter-kit#34]
Hello

I have followed closely each instruction in [React Native docs](https://reactnative.dev/docs/environment-setup) to set up the development environment (React Native CLI Quickstart > Windows > Android), on a machine running Windows 10 and another machine running a fresh install of Windows 11.

I then cloned this repository, followed each instruction (excluding the `npx pod-install` command since I'm on Windows) without modifying any file, the only exception being a `local.properties` file I added in `starter-kit\android\` with this one line inside: `sdk.dir="C:\Users\Fabio\\AppData\Local\Android\Sdk"`.

After connecting a physical device (Samsung SM-A505FN, running Android 11), which is listed in `adb devices` I tried running `npx react-native run-android`, which resulted in the app being built and installed on my device successfully.

As the app opens though I'm having a `TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[4], "@viro-community/react-viro").ViroConstants.TRACKING_NORMAL')` both in Metro and on my device, signaling an error in App.js at line 15.
The camera is being used and I can see "Initializing AR..."
This exact same error happens on both my machines, with multiple devices (Samsung Galaxy A50 with Android 11, Huawei P20 lite with Android 9, Honor Play with Android 9).

How can I solve this and have "Hello World" appear instead of "initializing AR..." without that error?

Here are some images (from the Samsung Galaxy A50 running Android 11)...
![Screenshot_20220330-100026_My Viro App](https://user-images.githubusercontent.com/34344402/160782276-5c59851e-43fe-4b49-aa6b-db63baef8563.png)
![Screenshot_20220330-100056_My Viro App](https://user-images.githubusercontent.com/34344402/160782308-47cfb94d-41ca-496d-b51e-ae1a4e5098c7.png)

**Comment by Dolpheyn** [comment]
You have to change to `import ViroTrackingStateConstants` instead of `import ViroConstants`.

**Comment by retr00h** [comment]
It works now, I can see the Hello World through AR.
Thank you!

**Comment by alex-voytko** [comment]
Hi, there! Thanks! I had the same problem and it was solved!
But now I can not see "Hello world!" because it unavailable ..
<img width="614" alt="Screenshot 2023-05-31 at 10 01 09" src="https://github.com/ViroCommunity/starter-kit/assets/70664414/dfb4e352-6e18-4fc8-9a21-4074fb5d04bc">
![photo_2023-05-31_10-07-26](https://github.com/ViroCommunity/starter-kit/assets/70664414/50bb42a1-db4e-436b-9e51-618a6bb83ce4)
<img width="326" alt="Screenshot 2023-05-31 at 10 09 39" src="https://github.com/ViroCommunity/starter-kit/assets/70664414/970b8722-cdb6-407a-8d52-259b59113445">

I am seeing my initial (preparing) text content because it moved to this condition: `state === ViroTrackingStateConstants.TRACKING_UNAVAILABLE)` Why unavailable ?
